apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: ticketcore.localhost
      http:
        paths:
          - path: /tickets/(.*) # Ловим всё после /tickets
            pathType: ImplementationSpecific # Для кастомных правил
            backend:
              service:
                name: ticket-service
                port:
                  number: 8081 # targetPort сервиса
#          - path: /notifications/(.*)
#            pathType: ImplementationSpecific
#            backend:
#              service:
#                name: notification-service
#                port:
#                  number: 8082